# Generated by Django 5.1.4 on 2024-12-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='time',
            new_name='dead_line',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='date',
            new_name='last_date',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='name',
            new_name='task',
        ),
    ]
